version: '3.7'
services:
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=any
      - MYSQL_DATABASE=credit-simulator          
      - MYSQL_USER=any                     
      - MYSQL_PASSWORD=any                  

  credit_simulator_api:
    image: node:16-alpine
    volumes:
      - ../:/credit_simulator_api
    working_dir: /credit_simulator_api
    depends_on:
      - database
    ports:
      - 3000:3000
      - 9229:9229
    env_file: ../.env
    environment:
      - APPLICATION_NAME=credit_simulator_api
      - PORT=3000
      - APP_ENVIRONMENT=development
      - DB_HOST=database
      - MYSQL_USER=any
      - MYSQL_ROOT_PASSWORD=any
      - MYSQL_DATABASE=credit-simulator
      - DB_PORT=3306
    command: ash -c "npm i --no-update-notifier && npm run dev && migration:run"
